package dns

import (
	"bytes"
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
	"time"
)

const (
	// ZoneDir is the directory containing generated BIND zone files.
	ZoneDir = "/var/named"
	// NamedConfInclude is the generated BIND zone include file.
	NamedConfInclude = "/etc/named/servika-zones.conf"
	// DNSSECKeyDir stores keys generated by the BIND DNSSEC policy.
	DNSSECKeyDir = "/var/named/dynamic"
)

// fqdn ensures target domain names for NS, MX, CNAME, SRV, and PTR records end with a dot.
// This prevents BIND from interpreting them as relative names and appending the zone name.
func fqdn(rtype, value string) string {
	t := strings.ToUpper(strings.TrimSpace(rtype))
	d := strings.TrimSpace(value)
	if t == "NS" || t == "MX" || t == "CNAME" || t == "SRV" || t == "PTR" {
		if !strings.HasSuffix(d, ".") {
			d = d + "."
		}
	}
	return d
}

func txtQuote(value string) string {
	data := []byte(value)
	if len(data) == 0 {
		return `""`
	}
	segments := make([]string, 0, (len(data)+254)/255)
	for len(data) > 0 {
		length := min(255, len(data))
		var escaped strings.Builder
		for _, b := range data[:length] {
			switch {
			case b == '\\' || b == '"':
				escaped.WriteByte('\\')
				escaped.WriteByte(b)
			case b < 32 || b == 127:
				fmt.Fprintf(&escaped, `\%03d`, b)
			default:
				escaped.WriteByte(b)
			}
		}
		segments = append(segments, `"`+escaped.String()+`"`)
		data = data[length:]
	}
	return strings.Join(segments, " ")
}

func rdata(recordType, value string) string {
	if strings.EqualFold(strings.TrimSpace(recordType), "TXT") {
		return txtQuote(value)
	}
	return fqdn(recordType, value)
}

var zoneTmpl = template.Must(template.New("z").Funcs(template.FuncMap{
	"rdata":   rdata,
	"soaHost": soaHost,
	"soaMail": soaMail,
}).Parse(`$TTL {{.SOA.TTL}}
@   IN  SOA {{soaHost .SOA.PrimaryNS}} {{soaMail .SOA.Hostmaster}} (
    {{.Serial}}  ; serial
    {{.SOA.Refresh}}  ; refresh
    {{.SOA.Retry}}  ; retry
    {{.SOA.Expire}}  ; expire
    {{.SOA.Minimum}}  ; minimum
)
{{range .Records}}{{.Name}}	{{.TTL}}	IN	{{.Type}}	{{if or (eq .Type "MX") (eq .Type "SRV")}}{{.Priority}} {{end}}{{rdata .Type .Value}}
{{end}}`))

func soaHost(primaryNS string) string {
	primaryNS = strings.TrimSpace(primaryNS)
	if primaryNS == "" {
		return "."
	}
	if !strings.HasSuffix(primaryNS, ".") {
		primaryNS += "."
	}
	return primaryNS
}

func soaMail(hostmaster string) string {
	hostmaster = strings.TrimSpace(hostmaster)
	if i := strings.Index(hostmaster, "@"); i >= 0 {
		hostmaster = hostmaster[:i] + "." + hostmaster[i+1:]
	}
	if hostmaster == "" {
		return "."
	}
	if !strings.HasSuffix(hostmaster, ".") {
		hostmaster += "."
	}
	return hostmaster
}

type zoneCtx struct {
	DomainName string
	Serial     string
	SOA        SOA
	Records    []Record
}

func readZoneSerial(path string) uint32 {
	body, err := os.ReadFile(path)
	if err != nil {
		return 0
	}
	for _, line := range strings.Split(string(body), "\n") {
		if !strings.Contains(line, "; serial") {
			continue
		}
		for _, field := range strings.Fields(line) {
			serial, parseErr := strconv.ParseUint(field, 10, 32)
			if parseErr == nil {
				return uint32(serial)
			}
		}
	}
	return 0
}

func nextSerialAt(old uint32, now time.Time) uint32 {
	base := uint32(now.UTC().Year()*1000000 + int(now.UTC().Month())*10000 + now.UTC().Day()*100)
	if old >= base && old < ^uint32(0) {
		return old + 1
	}
	return base
}

func nextSerial(old uint32) uint32 {
	return nextSerialAt(old, time.Now())
}

// WriteZone renders and validates the BIND zone file for a domain.
func WriteZone(ctx context.Context, db *sql.DB, domainID int64) error {
	var domainName string
	if err := db.QueryRowContext(ctx, `SELECT domain_name FROM domains WHERE id=?`, domainID).Scan(&domainName); err != nil {
		return err
	}
	rows, err := db.QueryContext(ctx,
		`SELECT id, domain_id, name, type, value, ttl, priority, enabled,
		   DATE_FORMAT(created_at,'%Y-%m-%d %H:%i') FROM dns_records
		 WHERE domain_id=? AND enabled=1 ORDER BY type, name`, domainID)
	if err != nil {
		return err
	}
	defer func() { _ = rows.Close() }()
	records := make([]Record, 0)
	for rows.Next() {
		record, err := scan(rows)
		if err == nil {
			records = append(records, record)
		}
	}
	if len(records) == 0 {
		return nil
	}

	if err := os.MkdirAll(ZoneDir, 0750); err != nil {
		return err
	}
	zonePath := filepath.Join(ZoneDir, domainName+".zone")
	serial := strconv.FormatUint(uint64(nextSerial(readZoneSerial(zonePath))), 10)

	soa := LoadSOA(ctx, db, domainID, domainName)
	var buf bytes.Buffer
	if err := zoneTmpl.Execute(&buf, zoneCtx{DomainName: domainName, Serial: serial, SOA: soa, Records: records}); err != nil {
		return err
	}
	tmpPath := zonePath + ".tmp"
	if err := os.WriteFile(tmpPath, buf.Bytes(), 0640); err != nil {
		return err
	}
	if out, err := exec.Command("named-checkzone", domainName, tmpPath).CombinedOutput(); err != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("named-checkzone: %s: %w", strings.TrimSpace(string(out)), err)
	}
	if previous, readErr := os.ReadFile(zonePath); readErr == nil {
		_ = os.WriteFile(zonePath+".bak", previous, 0640)
	}
	if err := os.Rename(tmpPath, zonePath); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	_, _ = exec.Command("chown", "named:named", zonePath).CombinedOutput()
	_, _ = exec.Command("restorecon", zonePath).CombinedOutput()

	if err := updateZoneIncludes(ctx, db); err != nil {
		return err
	}
	reloadNamed()
	return nil
}

// reloadNamed reloads BIND and validates the configuration before a restart fallback.
func reloadNamed() {
	if err := exec.Command("rndc", "reload").Run(); err == nil {
		return
	}
	if err := exec.Command("systemctl", "reload", "named").Run(); err == nil {
		return
	}
	if err := exec.Command("named-checkconf").Run(); err != nil {
		log.Printf("dns reload: named-checkconf failed; named restart skipped: %v", err)
		return
	}
	_ = exec.Command("systemctl", "restart", "named").Run()
}

func zoneIncludeStatement(domainName string, dnssec bool) string {
	statement := fmt.Sprintf(`zone "%s" { type master; file "%s/%s.zone"; allow-query { any; }; allow-transfer { none; };`,
		domainName, ZoneDir, domainName)
	if dnssec {
		statement += fmt.Sprintf(` dnssec-policy default; key-directory "%s"; inline-signing yes;`, DNSSECKeyDir)
	}
	return statement + " };\n"
}

func buildZoneIncludes(ctx context.Context, db *sql.DB) (string, error) {
	rows, err := db.QueryContext(ctx, `SELECT d.domain_name, COALESCE(d.dnssec_active,0) FROM domains d
	  WHERE EXISTS (SELECT 1 FROM dns_records r WHERE r.domain_id=d.id AND r.enabled=1)`)
	if err != nil {
		return "", err
	}
	defer func() { _ = rows.Close() }()
	var output strings.Builder
	output.WriteString("// Automatically generated by Servika\n")
	for rows.Next() {
		var domainName string
		var dnssec int
		if err := rows.Scan(&domainName, &dnssec); err != nil {
			return "", err
		}
		output.WriteString(zoneIncludeStatement(domainName, dnssec == 1))
	}
	if err := rows.Err(); err != nil {
		return "", err
	}
	return output.String(), nil
}

func updateZoneIncludes(ctx context.Context, db *sql.DB) error {
	content, err := buildZoneIncludes(ctx, db)
	if err != nil {
		return err
	}
	tmpPath := NamedConfInclude + ".tmp"
	if err := os.WriteFile(tmpPath, []byte(content), 0644); err != nil {
		return err
	}
	if output, checkErr := exec.Command("named-checkconf", tmpPath).CombinedOutput(); checkErr != nil {
		_ = os.Remove(tmpPath)
		return fmt.Errorf("validate generated zone include: %s: %w", strings.TrimSpace(string(output)), checkErr)
	}
	if err := os.Rename(tmpPath, NamedConfInclude); err != nil {
		_ = os.Remove(tmpPath)
		return err
	}
	_, _ = exec.Command("restorecon", NamedConfInclude).CombinedOutput()
	return nil
}

// HealZoneIncludes reapplies transfer restrictions and DNSSEC policy to every managed zone include.
func HealZoneIncludes(ctx context.Context, db *sql.DB) error {
	if err := updateZoneIncludes(ctx, db); err != nil {
		return err
	}
	reloadNamed()
	return nil
}

// DeleteZone removes a domain's BIND zone file and reloads the zone list.
func DeleteZone(ctx context.Context, db *sql.DB, domainName string) error {
	_ = os.Remove(filepath.Join(ZoneDir, domainName+".zone"))
	_ = updateZoneIncludes(ctx, db)
	reloadNamed()
	return nil
}
