package mail

import (
	"context"
	"fmt"
	"log"
	"os"
	"os/exec"
	"sort"
	"strings"

	"servika/internal/provisioner"
)

// Postfix and Dovecot each hold one certificate for the whole server, so a
// client connecting to mail.<domain> is shown a name that does not match and
// warns, or refuses outright. Both can select a certificate per requested name:
// Postfix through tls_server_sni_maps (3.4+), Dovecot through local_name blocks.
//
// The map is generated from the certificate files themselves. Nothing records
// which names are covered anywhere else, so nothing can drift out of sync with
// what is actually installed; an expired certificate simply stops appearing.

const (
	dovecotSNIConf = "/etc/dovecot/conf.d/20-servika-sni.conf"
	postfixSNIFile = "/etc/postfix/servika_sni"
	// The generated files are recognisable so an operator can tell at a glance
	// that editing them by hand is pointless.
	generatedHeader = "# Generated by Servika. Edits are overwritten; the source of truth is the\n" +
		"# set of installed mail certificates under the certificate root.\n"
)

// sniCommand runs a mail-stack tool. It is a variable so tests can observe the
// commands without a Postfix or Dovecot installation.
var sniCommand = func(name string, args ...string) ([]byte, error) {
	return exec.Command(name, args...).CombinedOutput() // #nosec G204 -- fixed tool names and paths this package composes; no caller input reaches argv.
}

// renderDovecotSNI builds the local_name blocks. Dovecot matches the name the
// client asked for, so every covered hostname needs its own block.
func renderDovecotSNI(covered map[string][]string) string {
	var out strings.Builder
	out.WriteString(generatedHeader)
	for _, domain := range sortedKeys(covered) {
		certPath, keyPath, _ := provisioner.MailCertificatePaths(domain)
		for _, host := range covered[domain] {
			fmt.Fprintf(&out, "local_name %s {\n  ssl_cert = <%s\n  ssl_key = <%s\n}\n", host, certPath, keyPath)
		}
	}
	return out.String()
}

// renderPostfixSNI builds the source form of the SNI table. postmap -F reads the
// named file and stores its CONTENT, and that file must start with the private
// key followed by the certificate chain, which is what the chain file is.
func renderPostfixSNI(covered map[string][]string) string {
	var out strings.Builder
	out.WriteString(generatedHeader)
	for _, domain := range sortedKeys(covered) {
		_, _, chainPath := provisioner.MailCertificatePaths(domain)
		for _, host := range covered[domain] {
			fmt.Fprintf(&out, "%s\t%s\n", host, chainPath)
		}
	}
	return out.String()
}

func sortedKeys(m map[string][]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// ApplySNI regenerates both configurations from the installed certificates and
// reloads the services.
//
// Each side is validated before it is kept: a rejected Dovecot configuration is
// rolled back, because Dovecot refuses to start on a bad file and that takes
// every mailbox on the server offline, not just the one being changed.
func ApplySNI() error {
	covered := provisioner.InstalledMailCertificates()
	if err := applyDovecotSNI(covered); err != nil {
		return err
	}
	return applyPostfixSNI(covered)
}

func applyDovecotSNI(covered map[string][]string) error {
	if _, err := exec.LookPath("doveconf"); err != nil {
		return nil // Dovecot is not installed on this host; nothing to configure.
	}
	body := renderDovecotSNI(covered)
	previous, hadPrevious := os.ReadFile(dovecotSNIConf) // #nosec G304 -- a fixed configuration path owned by this package.
	if hadPrevious == nil && string(previous) == body {
		return nil // Unchanged: do not reload a service for nothing.
	}
	// #nosec G306 -- a Dovecot drop-in it must read; it names key paths but holds no key material.
	if err := os.WriteFile(dovecotSNIConf, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write the Dovecot SNI configuration: %w", err)
	}
	if out, err := sniCommand("doveconf", "-n"); err != nil {
		restoreOrRemove(dovecotSNIConf, previous, hadPrevious == nil)
		return fmt.Errorf("doveconf rejected the SNI configuration, it was rolled back: %s", strings.TrimSpace(string(out)))
	}
	if out, err := sniCommand("systemctl", "reload", "dovecot"); err != nil {
		return fmt.Errorf("reload Dovecot: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func applyPostfixSNI(covered map[string][]string) error {
	if _, err := exec.LookPath("postmap"); err != nil {
		return nil // Postfix is not installed on this host.
	}
	body := renderPostfixSNI(covered)
	// #nosec G306 -- the table source names chain files; the key material stays in the chain files themselves, which are 0600.
	if err := os.WriteFile(postfixSNIFile, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write the Postfix SNI table: %w", err)
	}
	// -F is what makes this work: it stores the CONTENT of each named chain file
	// in the indexed table rather than the path.
	if out, err := sniCommand("postmap", "-F", "hash:"+postfixSNIFile); err != nil {
		return fmt.Errorf("build the Postfix SNI table: %s", strings.TrimSpace(string(out)))
	}
	if err := os.Chmod(postfixSNIFile+".db", 0o600); err != nil && !os.IsNotExist(err) {
		// The indexed table holds the private keys; it must not be world-readable.
		return fmt.Errorf("restrict the Postfix SNI table: %w", err)
	}
	if out, err := sniCommand("postconf", "-e", "tls_server_sni_maps=hash:"+postfixSNIFile); err != nil {
		return fmt.Errorf("point Postfix at the SNI table: %s", strings.TrimSpace(string(out)))
	}
	if out, err := sniCommand("systemctl", "reload", "postfix"); err != nil {
		return fmt.Errorf("reload Postfix: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func restoreOrRemove(path string, previous []byte, hadPrevious bool) {
	if hadPrevious {
		// #nosec G306,G703 -- restoring a fixed configuration path this package owns, exactly as it was found.
		_ = os.WriteFile(path, previous, 0o644)
		return
	}
	_ = os.Remove(path)
}

// HealMailSNI regenerates the SNI configuration at startup so an install that
// already has mail certificates picks them up without anyone reissuing, and so a
// certificate that expired stops being served.
func HealMailSNI(ctx context.Context) {
	if ctx.Err() != nil {
		return
	}
	if err := ApplySNI(); err != nil {
		log.Printf("mail sni heal: %v", err)
	}
}
