-- 0005 - SSL certificate paths (cert + key)
ALTER TABLE domains
  ADD COLUMN IF NOT EXISTS cert_path VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS key_path VARCHAR(255) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ssl_source VARCHAR(32) NOT NULL DEFAULT '';
