-- 0006 - service_plans (service packages) + domains.plan_id
CREATE TABLE IF NOT EXISTS service_plans (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL UNIQUE,
  description VARCHAR(255) NOT NULL DEFAULT '',
  disk_quota_mb INT NOT NULL DEFAULT 0,
  traffic_quota_mb INT NOT NULL DEFAULT 0,
  max_domain INT NOT NULL DEFAULT 0,
  max_db INT NOT NULL DEFAULT 0,
  max_email INT NOT NULL DEFAULT 0,
  max_ftp INT NOT NULL DEFAULT 0,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

ALTER TABLE domains
  ADD COLUMN IF NOT EXISTS plan_id BIGINT UNSIGNED NULL,
  ADD KEY IF NOT EXISTS ix_domains_plan (plan_id);
