CREATE TABLE IF NOT EXISTS domain_redis (
  domain_id BIGINT NOT NULL PRIMARY KEY,
  sk VARCHAR(32) NOT NULL,
  redis_pass VARCHAR(64) NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
