CREATE TABLE IF NOT EXISTS dns_template (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(253) NOT NULL,
  type VARCHAR(16) NOT NULL,
  value TEXT NOT NULL,
  ttl INT NOT NULL DEFAULT 3600,
  priority INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS dns_template_meta (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  soa_refresh INT NOT NULL DEFAULT 3600,
  soa_retry INT NOT NULL DEFAULT 900,
  soa_expire INT NOT NULL DEFAULT 1209600,
  soa_minimum INT NOT NULL DEFAULT 3600,
  soa_ttl INT NOT NULL DEFAULT 3600,
  dkim_selector VARCHAR(63) NOT NULL DEFAULT 'default',
  dkim_enabled TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO dns_template_meta (id)
SELECT 1 FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM dns_template_meta);

CREATE TABLE IF NOT EXISTS dkim_keys (
  domain_id BIGINT UNSIGNED NOT NULL,
  selector VARCHAR(63) NOT NULL DEFAULT 'default',
  private_key MEDIUMTEXT NOT NULL,
  public_key MEDIUMTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (domain_id, selector),
  CONSTRAINT fk_dkim_domain
    FOREIGN KEY (domain_id) REFERENCES domains(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
