ALTER TABLE domains ADD COLUMN IF NOT EXISTS parent_domain_id BIGINT UNSIGNED NULL;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS parked TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE domains ADD INDEX IF NOT EXISTS ix_domains_parent (parent_domain_id);
