# shellcheck shell=sh
# Servika jailed shell chroots hosting accounts in the servika-ssh group
Match Group servika-ssh
    ChrootDirectory /home/jails/%u
    X11Forwarding no
    AllowTcpForwarding no
    AllowAgentForwarding no
    PermitTunnel no
